parameters:
    locale: en
    secret: secret
    mocap_storage: "%kernel.root_dir%/data/mocap"
    content_storage: "%kernel.root_dir%/data/content"

imports:
    - { resource: database.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ["twig"]
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions"
    fragments:       ~
    http_method_override: true
    assets: ~

monolog:
    handlers:
        app:
            type: stream
            path: "%kernel.logs_dir%/app.log"
            level: warning
            channels: ['!doctrine']

        doctrine:
            type: stream
            path: '%kernel.logs_dir%/sql.log'
            level: warning
            channels: ['doctrine']

twig:
    cache: "%kernel.cache_dir%/twig"

gregwar_captcha: ~