doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   mysqli
                host:     mysql.idhostinger.com
                port:     3306
                dbname:   u884380406_mocap
                user:     u884380406_mocap
                password: f7X42lEKFw

                charset:  utf8
                default_table_options:
                    charset:  utf8
                    collate:  utf8_unicode_ci

                logging:  true

    orm:
        mappings:
            pips:
                type:   annotation
                dir:    '%kernel.root_dir%/../src'
                prefix: 'Jasati\MocapBundle\Model'

        auto_mapping: false
        auto_generate_proxy_classes: true
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies

        naming_strategy: doctrine.orm.naming_strategy.underscore

        metadata_cache_driver:  array
        query_cache_driver:     array
        result_cache_driver:    array